image: docker-reg.devops.xiaohongshu.com/data/maven-hercules:0.0.3
stages:
  - build

build:
  stage: build
  script:
    - cd command && mvn clean package -DskipTests -q && cd ..
    - scp -o StrictHostKeyChecking=false command/assemble/target/hercules-command.tar.gz root@ops-nginx-midware-prod-sh4-qc01:/data/nginx/html/deploy/hercules-command-$CI_COMMIT_TAG.tar.gz
  only:
    - tags
