// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oplogManager.proto

package oplogManagerPB;

public final class OplogManagerPB {
  private OplogManagerPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OplogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oplogManagerPB.Oplog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ns = 1;</code>
     * @return The ns.
     */
    java.lang.String getNs();
    /**
     * <code>string ns = 1;</code>
     * @return The bytes for ns.
     */
    com.google.protobuf.ByteString
        getNsBytes();

    /**
     * <code>fixed64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>.oplogManagerPB.Op op = 3;</code>
     * @return The enum numeric value on the wire for op.
     */
    int getOpValue();
    /**
     * <code>.oplogManagerPB.Op op = 3;</code>
     * @return The op.
     */
    oplogManagerPB.OperatorPB.Op getOp();

    /**
     * <code>string doc = 4;</code>
     * @return The doc.
     */
    java.lang.String getDoc();
    /**
     * <code>string doc = 4;</code>
     * @return The bytes for doc.
     */
    com.google.protobuf.ByteString
        getDocBytes();

    /**
     * <code>bool fromMigrate = 5;</code>
     * @return The fromMigrate.
     */
    boolean getFromMigrate();
  }
  /**
   * Protobuf type {@code oplogManagerPB.Oplog}
   */
  public static final class Oplog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oplogManagerPB.Oplog)
      OplogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Oplog.newBuilder() to construct.
    private Oplog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Oplog() {
      ns_ = "";
      op_ = 0;
      doc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Oplog();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Oplog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ns_ = s;
              break;
            }
            case 17: {

              timestamp_ = input.readFixed64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              op_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              doc_ = s;
              break;
            }
            case 40: {

              fromMigrate_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return oplogManagerPB.OplogManagerPB.internal_static_oplogManagerPB_Oplog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return oplogManagerPB.OplogManagerPB.internal_static_oplogManagerPB_Oplog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              oplogManagerPB.OplogManagerPB.Oplog.class, oplogManagerPB.OplogManagerPB.Oplog.Builder.class);
    }

    public static final int NS_FIELD_NUMBER = 1;
    private volatile java.lang.Object ns_;
    /**
     * <code>string ns = 1;</code>
     * @return The ns.
     */
    @java.lang.Override
    public java.lang.String getNs() {
      java.lang.Object ref = ns_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ns_ = s;
        return s;
      }
    }
    /**
     * <code>string ns = 1;</code>
     * @return The bytes for ns.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNsBytes() {
      java.lang.Object ref = ns_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>fixed64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int OP_FIELD_NUMBER = 3;
    private int op_;
    /**
     * <code>.oplogManagerPB.Op op = 3;</code>
     * @return The enum numeric value on the wire for op.
     */
    @java.lang.Override public int getOpValue() {
      return op_;
    }
    /**
     * <code>.oplogManagerPB.Op op = 3;</code>
     * @return The op.
     */
    @java.lang.Override public oplogManagerPB.OperatorPB.Op getOp() {
      @SuppressWarnings("deprecation")
      oplogManagerPB.OperatorPB.Op result = oplogManagerPB.OperatorPB.Op.valueOf(op_);
      return result == null ? oplogManagerPB.OperatorPB.Op.UNRECOGNIZED : result;
    }

    public static final int DOC_FIELD_NUMBER = 4;
    private volatile java.lang.Object doc_;
    /**
     * <code>string doc = 4;</code>
     * @return The doc.
     */
    @java.lang.Override
    public java.lang.String getDoc() {
      java.lang.Object ref = doc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        doc_ = s;
        return s;
      }
    }
    /**
     * <code>string doc = 4;</code>
     * @return The bytes for doc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDocBytes() {
      java.lang.Object ref = doc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        doc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMMIGRATE_FIELD_NUMBER = 5;
    private boolean fromMigrate_;
    /**
     * <code>bool fromMigrate = 5;</code>
     * @return The fromMigrate.
     */
    @java.lang.Override
    public boolean getFromMigrate() {
      return fromMigrate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ns_);
      }
      if (timestamp_ != 0L) {
        output.writeFixed64(2, timestamp_);
      }
      if (op_ != oplogManagerPB.OperatorPB.Op.NONE.getNumber()) {
        output.writeEnum(3, op_);
      }
      if (!getDocBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, doc_);
      }
      if (fromMigrate_ != false) {
        output.writeBool(5, fromMigrate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ns_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, timestamp_);
      }
      if (op_ != oplogManagerPB.OperatorPB.Op.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, op_);
      }
      if (!getDocBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, doc_);
      }
      if (fromMigrate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, fromMigrate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof oplogManagerPB.OplogManagerPB.Oplog)) {
        return super.equals(obj);
      }
      oplogManagerPB.OplogManagerPB.Oplog other = (oplogManagerPB.OplogManagerPB.Oplog) obj;

      if (!getNs()
          .equals(other.getNs())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (op_ != other.op_) return false;
      if (!getDoc()
          .equals(other.getDoc())) return false;
      if (getFromMigrate()
          != other.getFromMigrate()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NS_FIELD_NUMBER;
      hash = (53 * hash) + getNs().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + OP_FIELD_NUMBER;
      hash = (53 * hash) + op_;
      hash = (37 * hash) + DOC_FIELD_NUMBER;
      hash = (53 * hash) + getDoc().hashCode();
      hash = (37 * hash) + FROMMIGRATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFromMigrate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static oplogManagerPB.OplogManagerPB.Oplog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(oplogManagerPB.OplogManagerPB.Oplog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oplogManagerPB.Oplog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oplogManagerPB.Oplog)
        oplogManagerPB.OplogManagerPB.OplogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return oplogManagerPB.OplogManagerPB.internal_static_oplogManagerPB_Oplog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return oplogManagerPB.OplogManagerPB.internal_static_oplogManagerPB_Oplog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                oplogManagerPB.OplogManagerPB.Oplog.class, oplogManagerPB.OplogManagerPB.Oplog.Builder.class);
      }

      // Construct using oplogManagerPB.OplogManagerPB.Oplog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ns_ = "";

        timestamp_ = 0L;

        op_ = 0;

        doc_ = "";

        fromMigrate_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return oplogManagerPB.OplogManagerPB.internal_static_oplogManagerPB_Oplog_descriptor;
      }

      @java.lang.Override
      public oplogManagerPB.OplogManagerPB.Oplog getDefaultInstanceForType() {
        return oplogManagerPB.OplogManagerPB.Oplog.getDefaultInstance();
      }

      @java.lang.Override
      public oplogManagerPB.OplogManagerPB.Oplog build() {
        oplogManagerPB.OplogManagerPB.Oplog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public oplogManagerPB.OplogManagerPB.Oplog buildPartial() {
        oplogManagerPB.OplogManagerPB.Oplog result = new oplogManagerPB.OplogManagerPB.Oplog(this);
        result.ns_ = ns_;
        result.timestamp_ = timestamp_;
        result.op_ = op_;
        result.doc_ = doc_;
        result.fromMigrate_ = fromMigrate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof oplogManagerPB.OplogManagerPB.Oplog) {
          return mergeFrom((oplogManagerPB.OplogManagerPB.Oplog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(oplogManagerPB.OplogManagerPB.Oplog other) {
        if (other == oplogManagerPB.OplogManagerPB.Oplog.getDefaultInstance()) return this;
        if (!other.getNs().isEmpty()) {
          ns_ = other.ns_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.op_ != 0) {
          setOpValue(other.getOpValue());
        }
        if (!other.getDoc().isEmpty()) {
          doc_ = other.doc_;
          onChanged();
        }
        if (other.getFromMigrate() != false) {
          setFromMigrate(other.getFromMigrate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        oplogManagerPB.OplogManagerPB.Oplog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (oplogManagerPB.OplogManagerPB.Oplog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ns_ = "";
      /**
       * <code>string ns = 1;</code>
       * @return The ns.
       */
      public java.lang.String getNs() {
        java.lang.Object ref = ns_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ns_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ns = 1;</code>
       * @return The bytes for ns.
       */
      public com.google.protobuf.ByteString
          getNsBytes() {
        java.lang.Object ref = ns_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ns_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ns = 1;</code>
       * @param value The ns to set.
       * @return This builder for chaining.
       */
      public Builder setNs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ns = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNs() {
        
        ns_ = getDefaultInstance().getNs();
        onChanged();
        return this;
      }
      /**
       * <code>string ns = 1;</code>
       * @param value The bytes for ns to set.
       * @return This builder for chaining.
       */
      public Builder setNsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ns_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>fixed64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>fixed64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int op_ = 0;
      /**
       * <code>.oplogManagerPB.Op op = 3;</code>
       * @return The enum numeric value on the wire for op.
       */
      @java.lang.Override public int getOpValue() {
        return op_;
      }
      /**
       * <code>.oplogManagerPB.Op op = 3;</code>
       * @param value The enum numeric value on the wire for op to set.
       * @return This builder for chaining.
       */
      public Builder setOpValue(int value) {
        
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.oplogManagerPB.Op op = 3;</code>
       * @return The op.
       */
      @java.lang.Override
      public oplogManagerPB.OperatorPB.Op getOp() {
        @SuppressWarnings("deprecation")
        oplogManagerPB.OperatorPB.Op result = oplogManagerPB.OperatorPB.Op.valueOf(op_);
        return result == null ? oplogManagerPB.OperatorPB.Op.UNRECOGNIZED : result;
      }
      /**
       * <code>.oplogManagerPB.Op op = 3;</code>
       * @param value The op to set.
       * @return This builder for chaining.
       */
      public Builder setOp(oplogManagerPB.OperatorPB.Op value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        op_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.oplogManagerPB.Op op = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOp() {
        
        op_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object doc_ = "";
      /**
       * <code>string doc = 4;</code>
       * @return The doc.
       */
      public java.lang.String getDoc() {
        java.lang.Object ref = doc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          doc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string doc = 4;</code>
       * @return The bytes for doc.
       */
      public com.google.protobuf.ByteString
          getDocBytes() {
        java.lang.Object ref = doc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          doc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string doc = 4;</code>
       * @param value The doc to set.
       * @return This builder for chaining.
       */
      public Builder setDoc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        doc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string doc = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoc() {
        
        doc_ = getDefaultInstance().getDoc();
        onChanged();
        return this;
      }
      /**
       * <code>string doc = 4;</code>
       * @param value The bytes for doc to set.
       * @return This builder for chaining.
       */
      public Builder setDocBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        doc_ = value;
        onChanged();
        return this;
      }

      private boolean fromMigrate_ ;
      /**
       * <code>bool fromMigrate = 5;</code>
       * @return The fromMigrate.
       */
      @java.lang.Override
      public boolean getFromMigrate() {
        return fromMigrate_;
      }
      /**
       * <code>bool fromMigrate = 5;</code>
       * @param value The fromMigrate to set.
       * @return This builder for chaining.
       */
      public Builder setFromMigrate(boolean value) {
        
        fromMigrate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool fromMigrate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromMigrate() {
        
        fromMigrate_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oplogManagerPB.Oplog)
    }

    // @@protoc_insertion_point(class_scope:oplogManagerPB.Oplog)
    private static final oplogManagerPB.OplogManagerPB.Oplog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new oplogManagerPB.OplogManagerPB.Oplog();
    }

    public static oplogManagerPB.OplogManagerPB.Oplog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Oplog>
        PARSER = new com.google.protobuf.AbstractParser<Oplog>() {
      @java.lang.Override
      public Oplog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Oplog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Oplog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Oplog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public oplogManagerPB.OplogManagerPB.Oplog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oplogManagerPB_Oplog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oplogManagerPB_Oplog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022oplogManager.proto\022\016oplogManagerPB\032\016op" +
      "erator.proto\"h\n\005Oplog\022\n\n\002ns\030\001 \001(\t\022\021\n\ttim" +
      "estamp\030\002 \001(\006\022\036\n\002op\030\003 \001(\0162\022.oplogManagerP" +
      "B.Op\022\013\n\003doc\030\004 \001(\t\022\023\n\013fromMigrate\030\005 \001(\010B\020" +
      "B\016OplogManagerPBb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          oplogManagerPB.OperatorPB.getDescriptor(),
        });
    internal_static_oplogManagerPB_Oplog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_oplogManagerPB_Oplog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oplogManagerPB_Oplog_descriptor,
        new java.lang.String[] { "Ns", "Timestamp", "Op", "Doc", "FromMigrate", });
    oplogManagerPB.OperatorPB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
