
- hosts: SH4-Data-HDFS
  tasks:
    - name: deploy hercules jar
      unarchive:
        src: http://10.0.223.180:8000/deploy/hercules-command-{{tag}}.tar.gz
        dest: /home/data/hercules_temp_test_oplogJson
        copy: no
        owner: data